name: 🐛 Bug Report
description: Report a bug in cv4pve-api-dotnet
title: "[BUG] "
labels: ["bug", "needs investigation"]
body:
  - type: markdown
    attributes:
      value: |
        ## 🐛 Bug Report
        
        Thanks for taking the time to fill out this bug report!
        
        **Before submitting:** Search existing issues to avoid duplicates.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the issue briefly
      placeholder: Describe your issue!
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: What you expected to happen
      placeholder: Describe the expected behavior!
    validations:
      required: true
  - type: textarea
    id: code-sample
    attributes:
      label: Code sample
      description: |
        Paste your code here. **Remove passwords and API tokens!**
      placeholder: |
        var client = new PveClient("pve.local");
        await client.Login("user@pam", "***");
        var result = await client.Nodes["pve1"].Qemu[100].Config.VmConfig();
      render: csharp
    validations:
      required: true
  - type: textarea
    id: error-message
    attributes:
      label: Error message / Stack trace
      description: |
        Paste the complete error message and stack trace here.
        
        ⚠️ **ATTENTION: Remove sensitive data (passwords, API keys) before pasting!**
      placeholder: Paste the error message and stack trace here
      render: shell
    validations:
      required: false
  - type: input
    id: nuget-version
    attributes:
      label: NuGet Package Version
      description: Which version of the NuGet package are you using?
      placeholder: "e.g., 8.2.0"
    validations:
      required: true
  - type: input
    id: dotnet-version
    attributes:
      label: .NET Version
      description: Output of "dotnet --version"
      placeholder: "e.g., 8.0.100"
    validations:
      required: true
  - type: input
    id: proxmox-version
    attributes:
      label: Proxmox VE Version
      description: What version of Proxmox VE are you connecting to?
      placeholder: "e.g., 8.1.4"
    validations:
      required: true
  - type: dropdown
    id: package
    attributes:
      label: Affected Package
      description: Which package is causing the issue?
      options:
        - Corsinvest.ProxmoxVE.Api
        - Corsinvest.ProxmoxVE.Api.Extension
        - Corsinvest.ProxmoxVE.Api.Shared
        - Corsinvest.ProxmoxVE.Api.Shell
        - Corsinvest.ProxmoxVE.Api.Metadata
        - Not sure / Multiple packages
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Windows
        - Linux
        - macOS
        - Other
    validations:
      required: true
  - type: dropdown
    id: authentication
    attributes:
      label: Authentication Method
      description: How are you authenticating with Proxmox VE?
      options:
        - Username/Password
        - API Token
        - Username/Password with 2FA
        - Not applicable
    validations:
      required: true
  - type: checkboxes
    id: additional-info
    attributes:
      label: Additional Information
      options:
        - label: I have tested with the latest version available
        - label: I have searched existing issues and this is not a duplicate
        - label: I have removed all sensitive information from my report
        - label: I would like to submit a Pull Request to fix this issue
